services:
  sflow-normalizer:
    build: .
    env_file:
      - .env
    environment:
      - SFLOW_PORT=6343
      - NETFLOW_LISTEN_PORT=2055
    ports:
      - "${SFLOW_PORT:-6343}:6343/udp"
      - "${SFLOW_PORT:-6343}:6343/tcp"
      - "${NETFLOW_LISTEN_PORT:-2055}:2055/udp"
    restart: unless-stopped
